FROM    nginx:1.27-alpine

RUN  rm -rf /usr/share/nginx/html/*
ADD  ./default.conf /etc/nginx/conf.d/default.conf
ADD  ./ext  /usr/share/nginx/html/ext
ADD  ./lib  /usr/share/nginx/html/lib
ADD  ./all-deps.zip  /usr/share/nginx/html/
ADD  ./LICENSE /usr/share/nginx/html/
ADD  ./credits.html /usr/share/nginx/html/
ADD  ./ext-dependency-graph.pdf /usr/share/nginx/html/
ADD  ./setup-php-runtime.sh /usr/share/nginx/html/
