<?php
return [
    "libc6" => '>=2.35',
    "libgcc-s1" => '>= 3.0',
    "libstdc++6" => '>= 11',
    "libyaml-0-2" => '',
    "libssl3" => '',
    "libxml2" => '',
    "libmagickcore-6.q16-6" => '',
    "libmagickcore-6.q16-6-extra" => '',
    "libmagickcore-6.q16hdri-6" => '',
    "libmagickcore-6.q16hdri-6-extra" => '',
    "libmagickwand-6.q16-6" => '',
    "libmagickwand-6.q16hdri-6" => '',
    "libpng16-16" => '',
    "libjpeg8" => '',
    "libjpeg-turbo8" => '',
    "libfreetype6" => '',
    "libc-ares2" => '',
    "libpcre2-8-0" => '',
    "libsodium23" => '',
    "libcurl4" => '',
    "libmariadb3" => '',
    "libaio1" => '',
    "zlib1g" => '',
    "mime-support" => '',
    "tzdata" => '',
    "ucf" => '',
    "libargon2-1" => '',
    "libsqlite3-0" => '',
    "libbrotli1" => '',
    "libpq5" => '',
    "unixodbc" => '',
    "firebird3.0-common" => '',
    "libzstd1" => '',
    "libssh2-1" => '',
    "liburing2" => '',
    "libedit2" => '',
    "libmagic1" => '',
    'libonig5' => '',
    'libxslt1.1' => '',
    'libzip4' => '',
];
