<?php

declare(strict_types=1);

$project_dir = realpath(__DIR__ . '/../../');
$php_version_tag = trim(file_get_contents($project_dir . '/sapi/PHP-VERSION.conf'));

// The php.net release archive includes files generated by Bison and re2c.
// GitHub tag archives do not, which can silently mix a new grammar with stale
// generated parser/scanner sources when PHP is upgraded.
$php_source_folder = $project_dir . "/var/php-{$php_version_tag}";
$php_archive_file = $project_dir . "/pool/php-tar/php-release-{$php_version_tag}.tar.gz";
$php_archive_url = "https://www.php.net/distributions/php-{$php_version_tag}.tar.gz";
$download_dir = dirname($php_archive_file);

$run_command = static function (array $arguments): void {
    $command = implode(' ', array_map('escapeshellarg', $arguments));
    passthru($command, $status);
    if ($status !== 0) {
        throw new RuntimeException("Command failed with exit code {$status}: {$command}");
    }
};

$remove_directory = static function (string $directory) use ($run_command): void {
    if (is_dir($directory)) {
        $run_command(['rm', '-rf', $directory]);
    }
};

if (!is_dir($download_dir) && !mkdir($download_dir, 0755, true) && !is_dir($download_dir)) {
    throw new RuntimeException("Unable to create PHP archive directory: {$download_dir}");
}

$need_download = !is_file($php_archive_file) || filesize($php_archive_file) < 1024;
if ($need_download) {
    $temporary_archive = $php_archive_file . '.part';
    @unlink($temporary_archive);
    echo "downloading PHP release source {$php_version_tag}" . PHP_EOL;
    $run_command(['curl', '-fSL', $php_archive_url, '-o', $temporary_archive]);
    if (!is_file($temporary_archive) || filesize($temporary_archive) < 1024) {
        throw new RuntimeException("Downloaded PHP source archive is invalid: {$temporary_archive}");
    }
    if (!rename($temporary_archive, $php_archive_file)) {
        throw new RuntimeException("Unable to publish PHP source archive: {$php_archive_file}");
    }
} else {
    echo "PHP release source archive cached: {$php_archive_file}" . PHP_EOL;
}

$required_generated_files = [
    'configure',
    'Zend/zend_language_parser.c',
    'Zend/zend_language_parser.h',
    'Zend/zend_language_scanner.c',
];
$source_is_complete = is_file("{$php_source_folder}/configure.ac");
foreach ($required_generated_files as $required_file) {
    $source_is_complete = $source_is_complete && is_file("{$php_source_folder}/{$required_file}");
}

if (!$source_is_complete) {
    $remove_directory($php_source_folder);
    if (!mkdir($php_source_folder, 0755, true) && !is_dir($php_source_folder)) {
        throw new RuntimeException("Unable to create PHP source directory: {$php_source_folder}");
    }
    echo "unpacking PHP release source {$php_version_tag}" . PHP_EOL;
    $run_command([
        'tar', '-zxf', $php_archive_file, '--strip-components=1', '-C', $php_source_folder,
    ]);
}

foreach (array_merge(['configure.ac'], $required_generated_files) as $required_file) {
    if (!is_file("{$php_source_folder}/{$required_file}")) {
        throw new RuntimeException("PHP release source is missing required file: {$required_file}");
    }
}

return $php_source_folder;
