FROM alpine:3.18 as builder-all-library

RUN uname -a

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV TZ=Etc/UTC

ARG COMPOSER_MIRROR=""
ARG MIRROR=""


RUN test -f /etc/apk/repositories.save || cp /etc/apk/repositories /etc/apk/repositories.save

# setup source repo, install dependencies
RUN if [ "${MIRROR}" = "ustc" -o "${MIRROR}" = "china" ]; then { sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories ; } fi
RUN if [ "${MIRROR}" = "tuna" ]; then { sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories ; } fi


WORKDIR /work

RUN mkdir -p /usr/local/swoole-cli/etc/

ADD ./bin/runtime/php  /usr/local/bin/
ADD ./bin/runtime/composer  /usr/local/bin/
ADD ./bin/runtime/cacert.pem  /etc/ssl/certs/


ADD ./php.ini  /usr/local/swoole-cli/etc/

ADD ./  /work


RUN chmod a+x /usr/local/bin/php
RUN chmod a+x /usr/local/bin/composer


ENV CERT_FILE=/etc/ssl/certs/cacert.pem
# ENV CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV PHP_INI=/usr/local/swoole-cli/etc/php.ini

RUN alias php='php -d curl.cainfo="${CERT_FILE}" -d openssl.cafile="${CERT_FILE}"'

RUN echo "alias php='php -d curl.cainfo=\"\${CERT_FILE}\" -d openssl.cafile=\"\${CERT_FILE}\"'" >>/root/.bashrc

RUN sh sapi/quickstart/linux/alpine-init.sh --mirror ${MIRROR}



WORKDIR /work

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN if [ "${COMPOSER_MIRROR}" = "aliyun" ]; then { composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ ; } fi
RUN if [ "${COMPOSER_MIRROR}" = "tencent" -o "${COMPOSER_MIRROR}" = "china" ]; then { composer config -g repos.packagist composer https://mirrors.cloud.tencent.com/composer/ ; } fi

RUN composer update  --optimize-autoloader
RUN composer config -g --unset repos.packagist


RUN php prepare.php  +apcu +ds +xlswriter +ssh2 +uuid

RUN bash make-install-deps.sh

RUN bash make.sh all-library



FROM alpine:3.18

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV TZ=Etc/UTC

ARG COMPOSER_MIRROR=""
ARG MIRROR=""

# setup source repo, install dependencies
RUN cp /etc/apk/repositories /etc/apk/repositories.save

RUN if [ "${MIRROR}" = "ustc" -o "${MIRROR}" = "china" ]; then { sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories ; } fi
RUN if [ "${MIRROR}" = "tuna" ]; then { sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories ; } fi

RUN apk update && apk add --no-cache tini

WORKDIR /work


COPY --from=builder-all-library /usr/local/bin/php /usr/local/bin/php
COPY --from=builder-all-library /usr/local/bin/composer /usr/local/bin/composer
COPY --from=builder-all-library /etc/ssl/certs/cacert.pem /etc/ssl/certs/cacert.pem

COPY --from=builder-all-library  /usr/local/swoole-cli /usr/local/swoole-cli


RUN chmod a+x /usr/local/bin/php
RUN chmod a+x /usr/local/bin/composer

ENV CERT_FILE=/etc/ssl/certs/cacert.pem
# ENV CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV PHP_INI=/usr/local/swoole-cli/etc/php.ini



ENV PHP_INI=/usr/local/swoole-cli/etc/php.ini


RUN alias php='php -d curl.cainfo="${CERT_FILE}" -d openssl.cafile="${CERT_FILE}"'

RUN echo "alias php='php -d curl.cainfo=\"\${CERT_FILE}\" -d openssl.cafile=\"\${CERT_FILE}\"'" >>/root/.bashrc

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN test -f /etc/apk/repositories.save && cp -f /etc/apk/repositories.save /etc/apk/repositories

RUN rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

ENTRYPOINT ["tini", "--"]

