name: swoole-cli-linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        git submodule update --init
        SKIP_LIBRARY_DOWNLOAD=1 php prepare.php +mongodb +inotify
        chmod +x ./make.sh
    - name: build
      uses: addnab/docker-run-action@v3
      with:
        image: phpswoole/swoole_cli_os:1.4
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work
          ./make.sh config
          ./make.sh build
