name: swoole-cli-linux

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: SKIP_LIBRARY_DOWNLOAD=1 php prepare.php +mongodb +inotify
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: phpswoole/swoole_cli_os:1.4
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work
          chmod +x ./make.sh
          ./make.sh config
          ./make.sh build
