FROM arm64v8/alpine:3.18

ARG MIRROR=""

# setup source repo, install dependencies
RUN test -f /etc/apk/repositories.save || cp /etc/apk/repositories /etc/apk/repositories.save
RUN if [ "${MIRROR}" = "ustc" -o "${MIRROR}" = "china"   ]; then { sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories ; } fi
RUN if [ "${MIRROR}" = "tuna" ]; then { sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories ; } fi


RUN apk update
RUN apk upgrade
RUN apk add  vim
RUN apk add  alpine-sdk
RUN apk add  xz
RUN apk add  autoconf
RUN apk add  automake
RUN apk add  linux-headers
RUN apk add  clang
RUN apk add  clang-dev
RUN apk add  lld
RUN apk add  libtool
RUN apk add  cmake
RUN apk add  bison
RUN apk add  re2c
RUN apk add  bash
RUN apk add  tini
RUN apk add  libc++-static libltdl-static
WORKDIR /work

